name: market-ia-trading-bot
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas>=2.2
  - numpy>=1.26
  - scipy
  - scikit-learn>=1.4
  - lightgbm
  - fastparquet
  - pyarrow
  - matplotlib
  - ta
  - backtrader
  - joblib
  - tqdm
  - dvc
  - pip
  - pip:
      - yfinance
